// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Prisma 7's CLI (migrations, introspection, etc.) only reads a single
  // `datasource.url`, and it must be a *direct* (non-pooled) connection for
  // schema changes to work reliably. The app's runtime queries will use the
  // pooled DATABASE_URL separately, via the Prisma Client constructor.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
